CREATE TABLE C##my.clients (
  id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  father_name VARCHAR(255),
  birth_date DATE NOT NULL,
  address VARCHAR(255) NOT NULL,
  phone_number VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
)

CREATE TABLE C##my.cars_list (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  brand VARCHAR(255) NOT NULL,
  model VARCHAR(255) NOT NULL,
  year INT NOT NULL,
  color VARCHAR(255) NOT NULL,
  price INT NOT NULL,
  status varchar(50),
  PRIMARY KEY (id)
);

CREATE TABLE C##my.orders_list (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  client_id INT NOT NULL,
  car_id INT NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  price INT NOT NULL,
  day int not null,
  status varchar(50),
  PRIMARY KEY (id),
  FOREIGN KEY (client_id) REFERENCES C##my.clients (id),
  FOREIGN KEY (car_id) REFERENCES C##my.cars_list (id)
);

