--СОЗДАНИЕ ТРИГЕРА "сохранение истории сдачи в аренду авто"

CREATE TABLE c##my.cars_history (
  id number generated by default as identity,
  car_id int NOT NULL,
  client_id int not null,
  rent_start_date varchar(10),
  rent_end_date varchar(10),
  status varchar(50)
);

drop table c##my.cars_history

CREATE OR REPLACE TRIGGER cars_history_trig
AFTER INSERT ON C##my.orders_list
FOR EACH ROW
BEGIN

  INSERT INTO C##my.cars_history (
    client_id,
    car_id,
    rent_start_date,
    rent_end_date,
    status
    
  )
  VALUES (
    :new.client_id,
    :new.car_id,
    :new.start_date,
    :new.end_date,
    :new.status
  );
END;


-- Отчет 
SELECT * FROM C##my.cars_history
order by car_id,rent_start_date